"""initial migration

Revision ID: 237089f9458f
Revises: 
Create Date: 2021-07-20 00:38:19.173979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237089f9458f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('address_first', sa.String(length=64), nullable=True),
    sa.Column('address_last', sa.String(length=64), nullable=True),
    sa.Column('address_zipcode', sa.String(length=64), nullable=True),
    sa.Column('address_city', sa.String(length=64), nullable=True),
    sa.Column('address_state', sa.String(length=64), nullable=True),
    sa.Column('order_cost', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('payment_status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
