"""migration-7

Revision ID: 635b9e0a304b
Revises: 3037e05364d5
Create Date: 2021-07-11 20:03:54.278146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635b9e0a304b'
down_revision = '3037e05364d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('image', sa.String(length=64), nullable=True))
    op.add_column('carts', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'title')
    op.drop_column('carts', 'image')
    # ### end Alembic commands ###
