"""migration-5

Revision ID: d7727980369a
Revises: 3f598474090b
Create Date: 2021-07-10 23:20:28.634951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7727980369a'
down_revision = '3f598474090b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('item_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'item_count')
    # ### end Alembic commands ###
